version: '3.4'

services:
  scaffold.api:
    image: ${DOCKER_REGISTRY-}scaffoldapi
    build:
      context: .
      dockerfile: src/Scaffold.Api/Dockerfile
  db:
     image: "mcr.microsoft.com/mssql/server:2022-latest"
     ports:
      - "1433:1433"

     environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"
